### ISSUE TITLE
attachinterrupt compile error

### ISSUE THREAD

**Issue by JonathanFHill** [sparkfun/Qduino_Mini#29]
when attempting to use AttachInterrupt

C:\Users\Jonathan\AppData\Local\Temp\build4346342965207304710.tmp/core.a(WInterrupts.c.o): In function `__vector_7':
C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/WInterrupts.c:272: multiple definition of `__vector_7'
Qduino\Qduino.cpp.o:C:\Users\Jonathan\AppData\Roaming\Arduino15\packages\Qduino Mini\hardware\avr\1.0.3\libraries\Qduino/Qduino.cpp:315: first defined here
collect2.exe: error: ld returned 1 exit status
Error compiling.

**Comment by BrentWilkins** [comment]
Did the suggestion I posted on Hackster of updating to the current version work for you? You are running 1.0.3, and the current version is 1.0.8.

**Comment by JonathanFHill** [comment]
Yes thank you. Works perfectly. Please mark as resolved.

Sent from Outlook




On Wed, Nov 18, 2015 at 8:50 AM -0800, "Brent Wilkins" <notifications@github.com> wrote:












Did the suggestion I posted on Hackster of updating to the current version work for you? You are running 1.0.3, and the current version is 1.0.8.
